export interface SeedCategory {
  name: string;
  slug: string;
  description: string;
  order: number;
}

export interface SeedVariant {
  code?: string;
  sizeLabel: string;
  shape?: string;
  color?: string;
  unitPrice: number;
  dozenPrice: number;
  wholesalePrice: number;
  stock?: number;
}

export interface SeedProduct {
  sku: string;
  name: string;
  slug: string;
  description: string;
  material: string;
  categorySlug: string;
  mainImage: string;
  images?: string[];
  hasLogoOption: boolean;
  logoPriceExtra?: number;
  allowCustomSize: boolean;
  variants: SeedVariant[];
}

export const CATEGORIES_DATA: SeedCategory[] = [
  {
    name: "Bases de Torta MDF",
    slug: "bases-mdf",
    description: "Bases de corte láser en MDF 3mm laminado lavable blanco y wengué en variedad de formas y tamaños.",
    order: 1,
  },
  {
    name: "Minibases",
    slug: "minibases",
    description: "Minibases para porciones individuales, cheesecakes y postres en packs por 10 unidades.",
    order: 2,
  },
  {
    name: "Bases Rectangulares",
    slug: "bases-rectangulares",
    description: "Bases rectangulares de alta resistencia para tortas familiares e institucionales.",
    order: 3,
  },
  {
    name: "Bases con Diseños",
    slug: "bases-disenos",
    description: "Bases decorativas con siluetas de luna, corazones, flores y trébol.",
    order: 4,
  },
  {
    name: "Toppers para Pastel",
    slug: "toppers",
    description: "Toppers decorativos en acrílico espejado y MDF con vinil para cumpleaños y ocasiones especiales.",
    order: 5,
  },
  {
    name: "Apliques de Acrílico",
    slug: "apliques",
    description: "Apliques decorativos cortados a láser para detalles finos de repostería.",
    order: 6,
  },
  {
    name: "Cajas y Empaques",
    slug: "cajas",
    description: "Cajas de acetato con cinta decorativa, cajas de cartulina y cajas doradas para cupcakes.",
    order: 7,
  },
  {
    name: "Complementos y Utensilios",
    slug: "complementos",
    description: "Esferas decorativas, boquillas de repostería, mangas desechables, moldes y pirotinas.",
    order: 8,
  },
];

export const PRODUCTS_DATA: SeedProduct[] = [
  // 1. BASES MDF 3MM RIZADAS
  {
    sku: "BASE-MDF-RIZADA",
    name: "Base de Torta MDF 3mm — Forma Rizada",
    slug: "base-torta-mdf-rizada",
    description: "Base decorativa con borde rizado cortado a láser en MDF 3mm de alta densidad. Disponible en acabado Blanco laminado o Wengué oscuro. Apta para tortas pesadas y personalización con logo grabado.",
    material: "MDF 3mm laminado",
    categorySlug: "bases-mdf",
    mainImage: "/images/products/bases-mdf/formas-disponibles-bases.png",
    images: [
      "/images/products/bases-mdf/base-mdf-hero-muestrario.png",
      "/images/products/bases-mdf/base-mdf-blanco-wengue.png",
      "/images/products/bases-mdf/base-mdf-personalizada-logo.png",
      "/images/products/bases-mdf/ficha-tecnica-bases-mdf.png",
    ],
    hasLogoOption: true,
    logoPriceExtra: 0.20,
    allowCustomSize: true,
    variants: [
      { code: "BBRI-10", sizeLabel: "10 cm", shape: "Rizada", color: "Blanco", unitPrice: 0.20, dozenPrice: 0.16, wholesalePrice: 0.14 },
      { code: "BBRI-12", sizeLabel: "12 cm", shape: "Rizada", color: "Blanco", unitPrice: 0.26, dozenPrice: 0.21, wholesalePrice: 0.18 },
      { code: "BBRI-13", sizeLabel: "13 cm", shape: "Rizada", color: "Blanco", unitPrice: 0.30, dozenPrice: 0.25, wholesalePrice: 0.21 },
      { code: "BBRI-15", sizeLabel: "15 cm", shape: "Rizada", color: "Blanco", unitPrice: 0.44, dozenPrice: 0.36, wholesalePrice: 0.31 },
      { code: "BBRI-17", sizeLabel: "17 cm", shape: "Rizada", color: "Blanco", unitPrice: 0.55, dozenPrice: 0.46, wholesalePrice: 0.39 },
      { code: "BBRI-18", sizeLabel: "18 cm", shape: "Rizada", color: "Blanco", unitPrice: 0.62, dozenPrice: 0.52, wholesalePrice: 0.45 },
      { code: "BBRI-20", sizeLabel: "20 cm", shape: "Rizada", color: "Blanco", unitPrice: 0.75, dozenPrice: 0.64, wholesalePrice: 0.55 },
      { code: "BBRI-22", sizeLabel: "22 cm", shape: "Rizada", color: "Blanco", unitPrice: 0.85, dozenPrice: 0.72, wholesalePrice: 0.61 },
      { code: "BBRI-24", sizeLabel: "24 cm", shape: "Rizada", color: "Blanco", unitPrice: 1.05, dozenPrice: 0.90, wholesalePrice: 0.80 },
      { code: "BBRI-25", sizeLabel: "25 cm", shape: "Rizada", color: "Blanco", unitPrice: 1.15, dozenPrice: 1.00, wholesalePrice: 0.86 },
      { code: "BBRI-27", sizeLabel: "27 cm", shape: "Rizada", color: "Blanco", unitPrice: 1.35, dozenPrice: 1.16, wholesalePrice: 1.01 },
      { code: "BBRI-30", sizeLabel: "30 cm", shape: "Rizada", color: "Blanco", unitPrice: 1.65, dozenPrice: 1.40, wholesalePrice: 1.25 },
      { code: "BBRI-32", sizeLabel: "32 cm", shape: "Rizada", color: "Blanco", unitPrice: 1.85, dozenPrice: 1.58, wholesalePrice: 1.34 },
      { code: "BBRI-35", sizeLabel: "35 cm", shape: "Rizada", color: "Blanco", unitPrice: 2.30, dozenPrice: 1.96, wholesalePrice: 1.75 },
      { code: "BBRI-40", sizeLabel: "40 cm", shape: "Rizada", color: "Blanco", unitPrice: 3.00, dozenPrice: 2.56, wholesalePrice: 2.22 },
    ],
  },
  // 2. BASES MDF FORMAS CLÁSICAS
  {
    sku: "BASE-MDF-REDONDA",
    name: "Base de Torta MDF 3mm — Forma Redonda Clásica",
    slug: "base-torta-mdf-redonda",
    description: "Borde circular puro cortado a láser en MDF 3mm de alta resistencia. Acabado blanco lavable o wengué oscuro. Compatible con grabado láser de marca.",
    material: "MDF 3mm laminado",
    categorySlug: "bases-mdf",
    mainImage: "/images/products/bases-mdf/base-mdf-blanco-wengue.png",
    images: [
      "/images/products/bases-mdf/formas-disponibles-bases.png",
      "/images/products/bases-mdf/base-mdf-hero-muestrario.png",
      "/images/products/bases-mdf/base-mdf-personalizada-logo.png",
    ],
    hasLogoOption: true,
    logoPriceExtra: 0.20,
    allowCustomSize: true,
    variants: [
      { code: "BBRE-15", sizeLabel: "15 cm", shape: "Redonda", color: "Blanco", unitPrice: 0.44, dozenPrice: 0.36, wholesalePrice: 0.31 },
      { code: "BBRE-18", sizeLabel: "18 cm", shape: "Redonda", color: "Blanco", unitPrice: 0.62, dozenPrice: 0.52, wholesalePrice: 0.45 },
      { code: "BBRE-20", sizeLabel: "20 cm", shape: "Redonda", color: "Blanco", unitPrice: 0.75, dozenPrice: 0.64, wholesalePrice: 0.55 },
      { code: "BBRE-25", sizeLabel: "25 cm", shape: "Redonda", color: "Blanco", unitPrice: 1.15, dozenPrice: 1.00, wholesalePrice: 0.86 },
      { code: "BBRE-30", sizeLabel: "30 cm", shape: "Redonda", color: "Blanco", unitPrice: 1.65, dozenPrice: 1.40, wholesalePrice: 1.25 },
      { code: "BBRE-35", sizeLabel: "35 cm", shape: "Redonda", color: "Blanco", unitPrice: 2.30, dozenPrice: 1.96, wholesalePrice: 1.75 },
    ],
  },
  {
    sku: "BASE-MDF-CUADRADA",
    name: "Base de Torta MDF 3mm — Forma Cuadrada",
    slug: "base-torta-mdf-cuadrada",
    description: "Base cuadrada con esquinas rectas perfectas en MDF 3mm. Ideal para tortas cuadradas y estructuras modernas.",
    material: "MDF 3mm laminado",
    categorySlug: "bases-mdf",
    mainImage: "/images/products/bases-mdf/base-mdf-personalizada-logo.png",
    images: [
      "/images/products/bases-mdf/formas-disponibles-bases.png",
      "/images/products/bases-mdf/base-mdf-hero-muestrario.png",
    ],
    hasLogoOption: true,
    logoPriceExtra: 0.20,
    allowCustomSize: true,
    variants: [
      { code: "BBC-15", sizeLabel: "15 cm", shape: "Cuadrada", color: "Blanco", unitPrice: 0.44, dozenPrice: 0.36, wholesalePrice: 0.31 },
      { code: "BBC-20", sizeLabel: "20 cm", shape: "Cuadrada", color: "Blanco", unitPrice: 0.75, dozenPrice: 0.64, wholesalePrice: 0.55 },
      { code: "BBC-25", sizeLabel: "25 cm", shape: "Cuadrada", color: "Blanco", unitPrice: 1.15, dozenPrice: 1.00, wholesalePrice: 0.86 },
      { code: "BBC-30", sizeLabel: "30 cm", shape: "Cuadrada", color: "Blanco", unitPrice: 1.65, dozenPrice: 1.40, wholesalePrice: 1.25 },
      { code: "BBC-35", sizeLabel: "35 cm", shape: "Cuadrada", color: "Blanco", unitPrice: 2.30, dozenPrice: 1.96, wholesalePrice: 1.75 },
    ],
  },
  {
    sku: "BASE-MDF-CORAZON",
    name: "Base de Torta MDF 3mm — Forma Corazón",
    slug: "base-torta-mdf-corazon",
    description: "Silueta de corazón en corte láser MDF 3mm. Especial para tortas de aniversario, San Valentín y fechas románticas.",
    material: "MDF 3mm laminado",
    categorySlug: "bases-mdf",
    mainImage: "/images/products/bases-disenos/base-diseno-corazones.png",
    images: [
      "/images/products/bases-mdf/formas-disponibles-bases.png",
      "/images/products/bases-mdf/base-mdf-hero-muestrario.png",
    ],
    hasLogoOption: true,
    logoPriceExtra: 0.20,
    allowCustomSize: true,
    variants: [
      { code: "BBCO-15", sizeLabel: "15 cm", shape: "Corazón", color: "Blanco", unitPrice: 0.44, dozenPrice: 0.36, wholesalePrice: 0.31 },
      { code: "BBCO-20", sizeLabel: "20 cm", shape: "Corazón", color: "Blanco", unitPrice: 0.75, dozenPrice: 0.64, wholesalePrice: 0.55 },
      { code: "BBCO-25", sizeLabel: "25 cm", shape: "Corazón", color: "Blanco", unitPrice: 1.15, dozenPrice: 1.00, wholesalePrice: 0.86 },
      { code: "BBCO-30", sizeLabel: "30 cm", shape: "Corazón", color: "Blanco", unitPrice: 1.65, dozenPrice: 1.40, wholesalePrice: 1.25 },
    ],
  },
  // 3. MINIBASES CHEESECAKE
  {
    sku: "MINIBASES-PACK",
    name: "Minibases para Cheesecake y Postres (Pack 10 Unidades)",
    slug: "minibases-cheesecake-pack-10",
    description: "Pack de 10 unidades de minibases individuales. Disponibles en forma rizada, circular o cuadrada en 10cm, 12cm y 15cm.",
    material: "MDF 3mm laminado",
    categorySlug: "minibases",
    mainImage: "/images/products/minibases/minibase-cheesecake-rizada.png",
    images: [
      "/images/products/minibases/minibase-cheesecake-circular.png",
      "/images/products/minibases/minibase-cheesecake-cuadrada.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "MBR-10", sizeLabel: "10 cm Rizada (Pack 10)", shape: "Rizada", color: "Blanco", unitPrice: 2.20, dozenPrice: 2.00, wholesalePrice: 1.80 },
      { code: "MBR-12", sizeLabel: "12 cm Rizada (Pack 10)", shape: "Rizada", color: "Blanco", unitPrice: 3.30, dozenPrice: 3.00, wholesalePrice: 2.70 },
      { code: "MBR-15", sizeLabel: "15 cm Rizada (Pack 10)", shape: "Rizada", color: "Blanco", unitPrice: 4.40, dozenPrice: 4.00, wholesalePrice: 3.60 },
      { code: "MBCI-10", sizeLabel: "10 cm Circular (Pack 10)", shape: "Circular", color: "Blanco", unitPrice: 2.20, dozenPrice: 2.00, wholesalePrice: 1.80 },
      { code: "MBCI-12", sizeLabel: "12 cm Circular (Pack 10)", shape: "Circular", color: "Blanco", unitPrice: 3.30, dozenPrice: 3.00, wholesalePrice: 2.70 },
      { code: "MBCU-10", sizeLabel: "10 cm Cuadrada (Pack 10)", shape: "Cuadrada", color: "Blanco", unitPrice: 2.20, dozenPrice: 2.00, wholesalePrice: 1.80 },
      { code: "MBCU-12", sizeLabel: "12 cm Cuadrada (Pack 10)", shape: "Cuadrada", color: "Blanco", unitPrice: 3.30, dozenPrice: 3.00, wholesalePrice: 2.70 },
    ],
  },
  // 4. BASES RECTANGULARES
  {
    sku: "BASE-MDF-RECTANGULAR",
    name: "Base de Torta MDF 3mm — Rectangular",
    slug: "base-torta-mdf-rectangular",
    description: "Bases rectangulares reforzadas. Ideales para tortas rectangulares de brazo gitano, pasteles de plancha o banquetes. Medidas desde 30x15 hasta 35x45 cm.",
    material: "MDF 3mm laminado",
    categorySlug: "bases-rectangulares",
    mainImage: "/images/products/bases-rectangulares/base-rectangular-mdf-personalizada.png",
    images: [
      "/images/products/bases-mdf/base-mdf-hero-muestrario.png",
      "/images/products/bases-mdf/base-mdf-personalizada-logo.png",
    ],
    hasLogoOption: true,
    logoPriceExtra: 0.20,
    allowCustomSize: true,
    variants: [
      { code: "BBRT-30X15", sizeLabel: "30x15 cm", shape: "Rectangular", color: "Blanco", unitPrice: 0.75, dozenPrice: 0.65, wholesalePrice: 0.55 },
      { code: "BBRT-30X20", sizeLabel: "30x20 cm", shape: "Rectangular", color: "Blanco", unitPrice: 1.00, dozenPrice: 0.88, wholesalePrice: 0.75 },
      { code: "BBRT-30X25", sizeLabel: "30x25 cm", shape: "Rectangular", color: "Blanco", unitPrice: 1.25, dozenPrice: 1.10, wholesalePrice: 0.94 },
      { code: "BBRT-25X35", sizeLabel: "25x35 cm", shape: "Rectangular", color: "Blanco", unitPrice: 1.45, dozenPrice: 1.29, wholesalePrice: 1.09 },
      { code: "BBRT-30X40", sizeLabel: "30x40 cm", shape: "Rectangular", color: "Blanco", unitPrice: 1.95, dozenPrice: 1.77, wholesalePrice: 1.50 },
      { code: "BBRT-30X45", sizeLabel: "30x45 cm", shape: "Rectangular", color: "Blanco", unitPrice: 2.20, dozenPrice: 1.98, wholesalePrice: 1.69 },
      { code: "BBRT-35X45", sizeLabel: "35x45 cm", shape: "Rectangular", color: "Blanco", unitPrice: 2.60, dozenPrice: 2.31, wholesalePrice: 1.98 },
    ],
  },
  // 5. BASES CON DISEÑOS ESPECIALES
  {
    sku: "BASE-MDF-DISENOS",
    name: "Base de Torta MDF — Diseños Especiales (Luna, Corazones, Flores, Trébol)",
    slug: "base-torta-mdf-disenos-especiales",
    description: "Bases decorativas temáticas: Base Luna (BBL), Base Corazones (BBCP), Base Flores (BBF) y Base Trébol (BBT). Desde 15cm hasta 35cm.",
    material: "MDF 3mm laminado",
    categorySlug: "bases-disenos",
    mainImage: "/images/products/bases-disenos/base-diseno-coleccion.png",
    images: [
      "/images/products/bases-disenos/base-diseno-luna.png",
      "/images/products/bases-disenos/base-diseno-corazones.png",
      "/images/products/bases-disenos/base-diseno-flores.png",
      "/images/products/bases-disenos/base-diseno-trebol.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "BBL-15", sizeLabel: "15 cm (Luna)", shape: "Luna", color: "Blanco", unitPrice: 0.50, dozenPrice: 0.45, wholesalePrice: 0.41 },
      { code: "BBL-20", sizeLabel: "20 cm (Luna)", shape: "Luna", color: "Blanco", unitPrice: 0.90, dozenPrice: 0.80, wholesalePrice: 0.72 },
      { code: "BBL-25", sizeLabel: "25 cm (Luna)", shape: "Luna", color: "Blanco", unitPrice: 1.40, dozenPrice: 1.25, wholesalePrice: 1.13 },
      { code: "BBL-30", sizeLabel: "30 cm (Luna)", shape: "Luna", color: "Blanco", unitPrice: 1.95, dozenPrice: 1.75, wholesalePrice: 1.58 },
      { code: "BBCP-20", sizeLabel: "20 cm (Corazones)", shape: "Corazones", color: "Blanco", unitPrice: 0.90, dozenPrice: 0.80, wholesalePrice: 0.72 },
      { code: "BBF-20", sizeLabel: "20 cm (Flores)", shape: "Flores", color: "Blanco", unitPrice: 0.90, dozenPrice: 0.80, wholesalePrice: 0.72 },
      { code: "BBT-20", sizeLabel: "20 cm (Trébol)", shape: "Trébol", color: "Blanco", unitPrice: 0.90, dozenPrice: 0.80, wholesalePrice: 0.72 },
    ],
  },
  // 6. TOPPERS
  {
    sku: "TOPPER-ACRILICO-MDF",
    name: "Topper para Torta en Acrílico y MDF + Vinil",
    slug: "topper-torta-acrilico-mdf",
    description: "Toppers decorativos cortados a láser para cumpleaños, bautizos, comunión y fechas especiales. Más de 48 modelos disponibles en Acrílico Espejado o MDF con vinil.",
    material: "Acrílico espejado / MDF Vinil",
    categorySlug: "toppers",
    mainImage: "/images/products/toppers/topper-acrilico-espejo-dorado.png",
    images: [
      "/images/products/toppers/topper-mdf-vinil.png",
      "/images/products/toppers/modelos/topper-tac-cumpleanos-01.png",
      "/images/products/toppers/modelos/topper-tab-bautizo-comunion-01.png",
      "/images/products/toppers/modelos/topper-tav-fechas-especiales-01.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "TAC-6", sizeLabel: "6 cm (Acrílico)", shape: "Acrílico", unitPrice: 0.65, dozenPrice: 0.55, wholesalePrice: 0.47 },
      { code: "TAC-10", sizeLabel: "10 cm (Acrílico)", shape: "Acrílico", unitPrice: 0.95, dozenPrice: 0.80, wholesalePrice: 0.72 },
      { code: "TAC-15", sizeLabel: "15 cm (Acrílico)", shape: "Acrílico", unitPrice: 1.20, dozenPrice: 1.00, wholesalePrice: 0.90 },
      { code: "TAC-20", sizeLabel: "20 cm (Acrílico)", shape: "Acrílico", unitPrice: 1.75, dozenPrice: 1.50, wholesalePrice: 1.28 },
      { code: "TAC-25", sizeLabel: "25 cm (Acrílico)", shape: "Acrílico", unitPrice: 2.60, dozenPrice: 2.25, wholesalePrice: 1.91 },
      { code: "TMC-6", sizeLabel: "6 cm (MDF + Vinil)", shape: "MDF Vinil", unitPrice: 0.45, dozenPrice: 0.35, wholesalePrice: 0.30 },
      { code: "TMC-10", sizeLabel: "10 cm (MDF + Vinil)", shape: "MDF Vinil", unitPrice: 0.60, dozenPrice: 0.50, wholesalePrice: 0.43 },
      { code: "TMC-15", sizeLabel: "15 cm (MDF + Vinil)", shape: "MDF Vinil", unitPrice: 1.00, dozenPrice: 0.85, wholesalePrice: 0.72 },
      { code: "TMC-20", sizeLabel: "20 cm (MDF + Vinil)", shape: "MDF Vinil", unitPrice: 1.45, dozenPrice: 1.25, wholesalePrice: 1.06 },
      { code: "TMC-25", sizeLabel: "25 cm (MDF + Vinil)", shape: "MDF Vinil", unitPrice: 2.20, dozenPrice: 1.90, wholesalePrice: 1.62 },
    ],
  },
  {
    sku: "TOPPER-NUMERO-MDF",
    name: "Topper Número MDF 15cm Personalizado (1 al 10)",
    slug: "topper-numero-mdf-personalizado",
    description: "Topper números One, Two, Three... Ten (códigos TMDF001 al TMDF010) cortados a láser en MDF y toppers personalizados.",
    material: "MDF 3mm",
    categorySlug: "toppers",
    mainImage: "/images/products/toppers/topper-numeros-mdf-one-ten.png",
    images: [
      "/images/products/toppers/topper-mdf-numerico-1.png",
      "/images/products/toppers/topper-mdf-personalizado-2.png",
      "/images/products/toppers/topper-mdf-personalizado-3.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "TMDF-15", sizeLabel: "15 cm (Números 1-10)", shape: "Números 1-10", unitPrice: 2.80, dozenPrice: 2.50, wholesalePrice: 2.25 },
    ],
  },
  // 7. APLIQUES
  {
    sku: "APLIQUES-ACRILICO",
    name: "Apliques de Acrílico Decorativos (4cm a 15cm)",
    slug: "apliques-acrilico-decorativos",
    description: "Apliques en acrílico miniatura y estándar: cruces, mariposas, ángeles, cálices y siluetas para repostería fina.",
    material: "Acrílico brillante",
    categorySlug: "apliques",
    mainImage: "/images/products/apliques/aplique-acrilico-10cm-15cm-cruz.png",
    images: [
      "/images/products/apliques/aplique-acrilico-10cm-15cm-mariposa.png",
      "/images/products/apliques/aplique-acrilico-10cm-15cm-angel.png",
      "/images/products/apliques/aplique-acrilico-miniatura-4cm-6cm-01.png",
      "/images/products/apliques/aplique-acrilico-miniatura-4cm-6cm-02.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "APL-4", sizeLabel: "4 cm (Miniatura)", shape: "Aplique", unitPrice: 0.45, dozenPrice: 0.40, wholesalePrice: 0.35 },
      { code: "APL-5", sizeLabel: "5 cm (Miniatura)", shape: "Aplique", unitPrice: 0.55, dozenPrice: 0.50, wholesalePrice: 0.45 },
      { code: "APL-6", sizeLabel: "6 cm (Miniatura)", shape: "Aplique", unitPrice: 0.65, dozenPrice: 0.60, wholesalePrice: 0.52 },
      { code: "APL-10", sizeLabel: "10 cm (Estándar)", shape: "Aplique", unitPrice: 2.20, dozenPrice: 2.00, wholesalePrice: 1.80 },
      { code: "APL-15", sizeLabel: "15 cm (Grande)", shape: "Aplique", unitPrice: 2.80, dozenPrice: 2.50, wholesalePrice: 2.20 },
    ],
  },
  // 8. CAJAS Y EMPAQUES
  {
    sku: "CAJA-ACETATO-BLANCA",
    name: "Caja de Acetato con Tapa Blanca e Incluye Cinta",
    slug: "caja-acetato-tapa-blanca",
    description: "Caja transparente de acetato de alta claridad con base y tapa blanca. Incluye cinta decorativa de colores a elección.",
    material: "Acetato y Cartón rígido blanco",
    categorySlug: "cajas",
    mainImage: "/images/products/cajas/caja-acetato-tapa-blanca.png",
    images: [
      "/images/products/cajas/caja-acetato-tapa-transparente.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "CAB-17X20", sizeLabel: "17 cm ancho x 20 cm alto", shape: "Caja Acetato", unitPrice: 1.25, dozenPrice: 1.13, wholesalePrice: 0.90 },
      { code: "CAB-21X24", sizeLabel: "21.5 cm ancho x 24 cm alto", shape: "Caja Acetato", unitPrice: 1.75, dozenPrice: 1.58, wholesalePrice: 1.26 },
      { code: "CAB-25X31", sizeLabel: "25.3 cm ancho x 31 cm alto", shape: "Caja Acetato", unitPrice: 2.35, dozenPrice: 2.16, wholesalePrice: 1.94 },
      { code: "CAB-31X28", sizeLabel: "31.2 cm ancho x 28 cm alto", shape: "Caja Acetato", unitPrice: 2.80, dozenPrice: 2.55, wholesalePrice: 2.29 },
      { code: "CAB-35X25", sizeLabel: "35.2 cm ancho x 25 cm alto", shape: "Caja Acetato", unitPrice: 3.85, dozenPrice: 3.55, wholesalePrice: 3.20 },
    ],
  },
  {
    sku: "CAJA-ACETATO-TRANSPARENTE",
    name: "Caja de Acetato 100% Tapa Transparente con Cinta",
    slug: "caja-acetato-tapa-transparente",
    description: "Caja cilíndrica de acetato totalmente transparente. Permite vista panorámica de 360 grados de tortas decoradas. Incluye cinta decorativa.",
    material: "Acetato transparente",
    categorySlug: "cajas",
    mainImage: "/images/products/cajas/caja-acetato-tapa-transparente.png",
    images: [
      "/images/products/cajas/caja-acetato-tapa-blanca.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "CAT-17X20", sizeLabel: "17 cm ancho x 20 cm alto", shape: "Caja Acetato", unitPrice: 1.30, dozenPrice: 1.14, wholesalePrice: 0.92 },
      { code: "CAT-21X24", sizeLabel: "21.5 cm ancho x 24 cm alto", shape: "Caja Acetato", unitPrice: 2.00, dozenPrice: 1.83, wholesalePrice: 1.46 },
      { code: "CAT-25X31", sizeLabel: "25.3 cm ancho x 31 cm alto", shape: "Caja Acetato", unitPrice: 2.20, dozenPrice: 2.00, wholesalePrice: 1.80 },
      { code: "CAT-31X28", sizeLabel: "31.2 cm ancho x 28 cm alto", shape: "Caja Acetato", unitPrice: 2.90, dozenPrice: 2.65, wholesalePrice: 2.38 },
      { code: "CAT-35X25", sizeLabel: "35.2 cm ancho x 25 cm alto", shape: "Caja Acetato", unitPrice: 4.00, dozenPrice: 3.65, wholesalePrice: 3.28 },
    ],
  },
  {
    sku: "CAJA-CUPCAKES-CARTULINA",
    name: "Caja de Cartulina Blanca para Cupcakes",
    slug: "caja-cartulina-cupcakes",
    description: "Caja de fácil armado con base y separadores internos para 2, 4 o 6 cupcakes.",
    material: "Cartulina blanca reforzada",
    categorySlug: "cajas",
    mainImage: "/images/products/cajas/caja-cartulina-4-cupcakes.png",
    images: [
      "/images/products/cajas/caja-cartulina-2-cupcakes.png",
      "/images/products/cajas/caja-cartulina-6-cupcakes.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "CC2C", sizeLabel: "2 Cupcakes (16*9*7.5 cm)", shape: "2 servicios", unitPrice: 0.30, dozenPrice: 0.25, wholesalePrice: 0.22 },
      { code: "CC4C", sizeLabel: "4 Cupcakes (16*16*7.5 cm)", shape: "4 servicios", unitPrice: 0.40, dozenPrice: 0.35, wholesalePrice: 0.30 },
      { code: "CC6C", sizeLabel: "6 Cupcakes (24*16*7.5 cm)", shape: "6 servicios", unitPrice: 0.50, dozenPrice: 0.45, wholesalePrice: 0.38 },
    ],
  },
  {
    sku: "CAJA-CUPCAKES-DORADA",
    name: "Caja para Cupcakes Acabado Dorado",
    slug: "caja-cupcakes-dorado",
    description: "Caja elegante con acabado metalizado dorado brillante y visor para 2, 4 o 6 cupcakes.",
    material: "Cartulina laminada dorada",
    categorySlug: "cajas",
    mainImage: "/images/products/cajas/caja-cupcakes-dorado-4-servicios.png",
    images: [
      "/images/products/cajas/caja-cupcakes-dorado-2-servicios.png",
      "/images/products/cajas/caja-cupcakes-dorado-6-servicios.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "CCD2C", sizeLabel: "2 Cupcakes Dorada (16*9*7.5 cm)", shape: "2 servicios", unitPrice: 0.35, dozenPrice: 0.30, wholesalePrice: 0.26 },
      { code: "CCD4C", sizeLabel: "4 Cupcakes Dorada (16*16*7.5 cm)", shape: "4 servicios", unitPrice: 0.45, dozenPrice: 0.40, wholesalePrice: 0.35 },
      { code: "CCD6C", sizeLabel: "6 Cupcakes Dorada (24*16*7.5 cm)", shape: "6 servicios", unitPrice: 0.60, dozenPrice: 0.55, wholesalePrice: 0.48 },
    ],
  },
  {
    sku: "CAJA-KIT-TORTA-CUPCAKES",
    name: "Caja Kit Torta + 5 Cupcakes + Cinta",
    slug: "caja-kit-torta-cupcakes-cinta",
    description: "Caja combinada con capacidad para 5 cupcakes y 1 mini torta de 10cm. Incluye cinta decorativa surtida.",
    material: "Cartulina y ventana de acetato",
    categorySlug: "cajas",
    mainImage: "/images/products/cajas/caja-kit-torta-cupcakes-cinta.png",
    images: [
      "/images/products/cajas/caja-mdf-kit-torta-porta-flores-30x30.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "CKT5C", sizeLabel: "Kit Torta 10cm + 5 Cupcakes", shape: "Kit", unitPrice: 1.50, dozenPrice: 1.36, wholesalePrice: 1.20 },
    ],
  },
  {
    sku: "CAJA-HALAR-VARIOS-COLORES",
    name: "Caja Halar con Visor 11x9.2 cm",
    slug: "caja-halar-varios-colores",
    description: "Caja de halar moderna en colores vibrantes (Roja, Rosa y Mostaza) de 11*9.2 cm.",
    material: "Cartulina premium con ventana",
    categorySlug: "cajas",
    mainImage: "/images/products/cajas/caja-halar-roja-11x9.png",
    images: [
      "/images/products/cajas/caja-halar-rosa-11x9.png",
      "/images/products/cajas/caja-halar-mostaza-11x9.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "CHR11X9", sizeLabel: "11*9.2 cm (Roja)", shape: "Halar", color: "Rojo", unitPrice: 0.35, dozenPrice: 0.30, wholesalePrice: 0.26 },
      { code: "CHRO11X9", sizeLabel: "11*9.2 cm (Rosa)", shape: "Halar", color: "Rosa", unitPrice: 0.35, dozenPrice: 0.30, wholesalePrice: 0.26 },
      { code: "CHM11X9", sizeLabel: "11*9.2 cm (Mostaza)", shape: "Halar", color: "Mostaza", unitPrice: 0.35, dozenPrice: 0.30, wholesalePrice: 0.26 },
    ],
  },
  {
    sku: "CAJAS-ACETATO-CUADRADAS",
    name: "Cajas de Acetato Cuadradas (Individuales y con Base)",
    slug: "cajas-acetato-cuadradas",
    description: "Mini cajas de acetato transparentes cuadradas para postres individuales y detalles gourmet.",
    material: "Acetato y cartulina",
    categorySlug: "cajas",
    mainImage: "/images/products/cajas/mini-caja-acetato-cuadrada-9x9x9.png",
    images: [
      "/images/products/cajas/caja-acetato-cuadrada-halar-cartulina-11x11x17.png",
      "/images/products/cajas/caja-acetato-cuadrada-1-cuerpo-10x10x8.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "CA9X9", sizeLabel: "Mini Acetato 9x9x9 cm", shape: "Cuadrada", unitPrice: 0.80, dozenPrice: 0.70, wholesalePrice: 0.60 },
      { code: "CA11X11", sizeLabel: "Acetato Halar + Cartulina 11x11x17 cm", shape: "Torre", unitPrice: 0.95, dozenPrice: 0.80, wholesalePrice: 0.70 },
      { code: "CA10X10", sizeLabel: "Acetato Cuadrada 1 Cuerpo 10x10x8 cm", shape: "Cuadrada", unitPrice: 1.05, dozenPrice: 0.90, wholesalePrice: 0.78 },
    ],
  },
  {
    sku: "CAJA-MDF-KIT-FLORES",
    name: "Caja Kit MDF Torta 30x30 con Porta Flores",
    slug: "caja-mdf-kit-flores-torta",
    description: "Caja estructural en MDF corte láser medidas 30x30 cm con compartimiento para base de torta 15cm y arreglos florales.",
    material: "MDF 3mm",
    categorySlug: "cajas",
    mainImage: "/images/products/cajas/caja-mdf-kit-torta-porta-flores-30x30.png",
    images: [
      "/images/products/cajas/caja-mdf-20x15-visor.png",
      "/images/products/cajas/caja-mdf-20x15-decorada.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "CKT001", sizeLabel: "Kit Torta 30x30 con Porta Flores", shape: "Caja MDF", unitPrice: 5.50, dozenPrice: 5.00, wholesalePrice: 4.50 },
      { code: "CMDF2015", sizeLabel: "Caja MDF 20x15 Visor", shape: "Caja MDF", unitPrice: 1.75, dozenPrice: 1.50, wholesalePrice: 1.30 },
    ],
  },
  // 9. COMPLEMENTOS: ESFERAS, UTENSILIOS Y PIROTINAS
  {
    sku: "ESFERAS-DECORATIVAS-PACK",
    name: "Esferas Decorativas Plásticas para Pastel (Pack 20 Unidades)",
    slug: "esferas-decorativas-plasticas-pack-20",
    description: "Pack de 20 esferas decorativas en 4 tamaños variados (2, 2.5, 3 y 4 cm). Disponibles en Dorado, Plateado, Rosa, Rojo, Azul Claro, Verde Claro, Blanco y Fucsia.",
    material: "Plástico decorativo",
    categorySlug: "complementos",
    mainImage: "/images/products/complementos/esfera-decorativa-dorado-pack20.png",
    images: [
      "/images/products/complementos/esfera-decorativa-plateado-pack20.png",
      "/images/products/complementos/esfera-decorativa-rosa-pack20.png",
      "/images/products/complementos/esfera-decorativa-rojo-pack20.png",
      "/images/products/complementos/esfera-decorativa-azul-claro-pack20.png",
      "/images/products/complementos/esfera-decorativa-verde-claro-pack20.png",
      "/images/products/complementos/esfera-decorativa-blanca-pack20.png",
      "/images/products/complementos/esfera-decorativa-fucsia-pack20.png",
      "/images/products/complementos/set-esferas-abanico-surtido.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "EDPD20", sizeLabel: "Dorado (Pack 20 pzs)", shape: "Esferas 2/2.5/3/4cm", color: "Dorado", unitPrice: 1.65, dozenPrice: 1.46, wholesalePrice: 1.30 },
      { code: "EDPP20", sizeLabel: "Plateado (Pack 20 pzs)", shape: "Esferas 2/2.5/3/4cm", color: "Plateado", unitPrice: 1.65, dozenPrice: 1.46, wholesalePrice: 1.30 },
      { code: "EDPRS20", sizeLabel: "Rosa (Pack 20 pzs)", shape: "Esferas 2/2.5/3/4cm", color: "Rosa", unitPrice: 1.65, dozenPrice: 1.46, wholesalePrice: 1.30 },
      { code: "EDPR20", sizeLabel: "Rojo (Pack 20 pzs)", shape: "Esferas 2/2.5/3/4cm", color: "Rojo", unitPrice: 1.65, dozenPrice: 1.46, wholesalePrice: 1.30 },
      { code: "EDPA20", sizeLabel: "Azul Claro (Pack 20 pzs)", shape: "Esferas 2/2.5/3/4cm", color: "Azul Claro", unitPrice: 1.65, dozenPrice: 1.46, wholesalePrice: 1.30 },
      { code: "EDPV20", sizeLabel: "Verde Claro (Pack 20 pzs)", shape: "Esferas 2/2.5/3/4cm", color: "Verde Claro", unitPrice: 1.65, dozenPrice: 1.46, wholesalePrice: 1.30 },
      { code: "EDPB20", sizeLabel: "Blanco (Pack 20 pzs)", shape: "Esferas 2/2.5/3/4cm", color: "Blanco", unitPrice: 1.65, dozenPrice: 1.46, wholesalePrice: 1.30 },
      { code: "EDPF20", sizeLabel: "Fucsia (Pack 20 pzs)", shape: "Esferas 2/2.5/3/4cm", color: "Fucsia", unitPrice: 1.65, dozenPrice: 1.46, wholesalePrice: 1.30 },
      { code: "SEAS", sizeLabel: "Set Esferas + Abanico Surtido", shape: "Set Surtido", unitPrice: 3.30, dozenPrice: 3.00, wholesalePrice: 2.70 },
    ],
  },
  {
    sku: "UTENSILIOS-CORTADORES",
    name: "Cortadores y Moldes para Repostería",
    slug: "cortadores-y-moldes-reposteria",
    description: "Sets de cortadores para galletas en círculo (pack 5 pzs), cortador acero margarita (pack 3 pzs) y set moldes figuras (pack 12 pzs).",
    material: "Acero inoxidable y plástico apto alimentos",
    categorySlug: "complementos",
    mainImage: "/images/products/complementos/cortador-galleta-circulo-pack5.png",
    images: [
      "/images/products/complementos/cortador-acero-margarita-pack3.png",
      "/images/products/complementos/set-moldes-figuras-pack12.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "CGC5", sizeLabel: "Cortador Galleta Círculo (5 pzs)", shape: "Círculo", unitPrice: 1.20, dozenPrice: 1.00, wholesalePrice: 0.85 },
      { code: "CAM3", sizeLabel: "Cortador Acero Margarita (3 pzs)", shape: "Margarita", unitPrice: 2.65, dozenPrice: 2.37, wholesalePrice: 2.10 },
      { code: "SMF12", sizeLabel: "Set Moldes Figuras (12 pzs)", shape: "Figuras", unitPrice: 2.30, dozenPrice: 2.00, wholesalePrice: 1.80 },
    ],
  },
  {
    sku: "BOQUILLAS-REPOSTERIA",
    name: "Sets de Boquillas para Decoración de Pasteles",
    slug: "sets-boquillas-reposteria",
    description: "Boquillas de precisión en acero para escribir, flores y bordes. Sets de 6, 9, 12 y 20 piezas con acople, y boquillas grandes con manga.",
    material: "Acero inoxidable",
    categorySlug: "complementos",
    mainImage: "/images/products/complementos/set-boquillas-pequenas-pack12.png",
    images: [
      "/images/products/complementos/set-boquillas-pequenas-pack6.png",
      "/images/products/complementos/set-boquillas-pequenas-pack9.png",
      "/images/products/complementos/set-boquillas-acople-pack20.png",
      "/images/products/complementos/set-boquillas-acero-escribir-pack5.png",
      "/images/products/complementos/set-boquillas-grandes-manga-pack10.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "SBP001", sizeLabel: "Set Boquillas Pequeñas (6 pzs)", shape: "6 Pzs", unitPrice: 2.00, dozenPrice: 1.77, wholesalePrice: 1.55 },
      { code: "SBP002", sizeLabel: "Set Boquillas Pequeñas (9 pzs)", shape: "9 Pzs", unitPrice: 2.30, dozenPrice: 2.00, wholesalePrice: 1.80 },
      { code: "SBP003", sizeLabel: "Set Boquillas Pequeñas (12 pzs)", shape: "12 Pzs", unitPrice: 2.55, dozenPrice: 2.25, wholesalePrice: 2.00 },
      { code: "SBP004", sizeLabel: "Set Boquillas + Acople (20 pzs)", shape: "20 Pzs", unitPrice: 3.40, dozenPrice: 3.00, wholesalePrice: 2.70 },
      { code: "SBP005", sizeLabel: "Boquillas Acero para Escribir (5 pzs)", shape: "5 Pzs Escribir", unitPrice: 3.40, dozenPrice: 3.00, wholesalePrice: 2.70 },
      { code: "SBG001", sizeLabel: "Set Boquillas Grandes + Manga (10 pzs)", shape: "10 Pzs + Manga", unitPrice: 4.10, dozenPrice: 3.70, wholesalePrice: 3.35 },
    ],
  },
  {
    sku: "MANGAS-DESECHABLES-PACK",
    name: "Mangas Plásticas Desechables para Repostería (Pack 100 Unidades)",
    slug: "mangas-plasticas-desechables-pack-100",
    description: "Mangas de repostería desechables de alta resistencia y flexibilidad. Pack por 100 piezas en 25cm, 30cm y 35cm.",
    material: "Plástico grado alimenticio",
    categorySlug: "complementos",
    mainImage: "/images/products/complementos/manga-plastica-desechable-30cm.png",
    images: [
      "/images/products/complementos/manga-plastica-desechable-25cm.png",
      "/images/products/complementos/manga-plastica-desechable-35cm.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "MPD25", sizeLabel: "25 cm (Pack 100 pzs)", shape: "25 cm", unitPrice: 1.70, dozenPrice: 1.50, wholesalePrice: 1.35 },
      { code: "MPD30", sizeLabel: "30 cm (Pack 100 pzs)", shape: "30 cm", unitPrice: 2.05, dozenPrice: 1.85, wholesalePrice: 1.65 },
      { code: "MPD35", sizeLabel: "35 cm (Pack 100 pzs)", shape: "35 cm", unitPrice: 2.50, dozenPrice: 2.25, wholesalePrice: 2.00 },
    ],
  },
  {
    sku: "PIROTINAS-BLANCAS-PACK",
    name: "Pirotinas Color Entero Blanco y Diseños Especiales (Pack 100 Unidades)",
    slug: "pirotinas-blancas-pack-100",
    description: "Pirotinas blancas aptas para horneado en diferentes números (#6, #7, #8 y #10) y modelos especiales con filo dorado para cupcakes.",
    material: "Papel antigrasa para horneado",
    categorySlug: "complementos",
    mainImage: "/images/products/complementos/pirotina-blanco-numero-8-pack100.png",
    images: [
      "/images/products/complementos/pirotina-blanco-numero-6-pack100.png",
      "/images/products/complementos/pirotina-blanco-numero-7-pack100.png",
      "/images/products/complementos/pirotina-blanco-numero-10-pack100.png",
      "/images/products/complementos/pirotina-cupcake-dia-especial-pack100.png",
      "/images/products/complementos/pirotina-cupcake-diseno-oro-pack100.png",
    ],
    hasLogoOption: false,
    allowCustomSize: false,
    variants: [
      { code: "PB6001", sizeLabel: "Pirotina #6 Blanco (Pack 100)", shape: "Ancho 2.5cm, Alto 1.75cm", unitPrice: 0.60, dozenPrice: 0.50, wholesalePrice: 0.45 },
      { code: "PB7001", sizeLabel: "Pirotina #7 Blanco (Pack 100)", shape: "Ancho 3cm, Alto 2cm", unitPrice: 0.70, dozenPrice: 0.60, wholesalePrice: 0.52 },
      { code: "PB8001", sizeLabel: "Pirotina #8 Blanco (Pack 100)", shape: "Ancho 3.5cm, Alto 2.25cm", unitPrice: 0.75, dozenPrice: 0.65, wholesalePrice: 0.58 },
      { code: "PB1001", sizeLabel: "Pirotina #10 Blanco (Pack 100)", shape: "Ancho 5cm, Alto 3.5cm", unitPrice: 0.90, dozenPrice: 0.80, wholesalePrice: 0.70 },
      { code: "PDE001", sizeLabel: "Pirotina Cupcake Día Especial Modelo 1 (Pack 100)", shape: "#10 Especial", unitPrice: 1.35, dozenPrice: 1.20, wholesalePrice: 1.05 },
      { code: "PDE002", sizeLabel: "Pirotina Cupcake Día Especial Modelo 2 (Pack 100)", shape: "#10 Especial", unitPrice: 1.35, dozenPrice: 1.20, wholesalePrice: 1.05 },
    ],
  },
];
